on:
  repository_dispatch:
    types: [design_tokens]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::set-output name=filename::${{ github.event.client_payload.filename }}"
        id: filename
      - run: mkdir tokens
      - uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ steps.filename.outputs.filename }}
          dir: "tokens/"
          json: |
            ${{ github.event.client_payload.tokens }}
      - run: |
          jq . tokens/${{ steps.filename.outputs.filename }}
