on:
  repository_dispatch:
    types: [design_tokens]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo $MESSAGE
        env:
          MESSAGE: ${{ github.event.client_payload }}
