on:
  repository_dispatch:
    types: [design_tokens]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.event_type }}
      - run: echo ${{ github.event.client_payload }}
