on:
  repository_dispatch:
    types: [design_tokens]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
