on:
  repository_dispatch:
    types: [design_tokens]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: jsdaniell/create-json@1.1.2
        with:
          name: "figma.tokens.json"
          json: |
            ${{ github.event.client_payload }}
      - run: jq . figma.tokens.json
